name: Count lines of code (cloc)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    # https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v3

    # https://github.com/actions/setup-go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # https://github.com/boyter/scc
    - name: Install SCC
      run: go install github.com/boyter/scc@latest
    
    # https://github.com/boyter/scc#usage
    - name: Count lines of code
      run: scc --no-cocomo -c -i dart --by-file
