name: Cloc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install SCC
      run: go install github.com/boyter/scc@latest

    - name: Count lines of code
      run: scc --no-cocomo -c -i dart
